### ISSUE TITLE
code under the dataset folder is missing

### ISSUE THREAD

**Issue by CarinaL99** [freshman97/LinTransUNet#1]
Could you please provide the code under the dataset folder?

**Comment by freshman97** [comment]
Sure, we will publish it soon after organization. Thank you for pointing it out.

**Comment by freshman97** [comment]
Hi, sorry for the delay. We have uploaded the dataset code under /dataset folder. In the meanwhile, we will combine the whole project into the nnUNet style for more convenient use in the future.
