### ISSUE TITLE
how to test the final model.pt

### ISSUE THREAD

**Issue by LimxRabbit** [freshman97/LinTransUNet#2]
hi~sorry to interrupt, i have trained my own model and saved as model.pt, can you tell me how to test the performance of this model! thanks!!!

**Comment by freshman97** [comment]
There are two ways: one is directly using the inference in training code in the initial version, or you can try the nnUNet branch, which combines the lintransformer with the nnUNet framework, which contains full pre-processing and evaluation codes.
